# server.py
import hashlib

# Global variable for SECRET_KEY to be set by input
SECRET_KEY_GLOBAL = b''

def get_secret_key_from_input():
    """Gets the secret key from user input and sets it globally."""
    global SECRET_KEY_GLOBAL
    while True:
        key_str = input("Enter the SECRET_KEY for the server: ")
        if key_str:
            SECRET_KEY_GLOBAL = key_str.encode('utf-8') # Encode to bytes
            print(f"Server will use SECRET_KEY: {SECRET_KEY_GLOBAL.decode()} (length: {len(SECRET_KEY_GLOBAL)})")
            break
        else:
            print("SECRET_KEY cannot be empty. Please enter a value.")

def generate_mac(message: bytes) -> str:
    """Generates a MAC using the insecure H(secret || message) construction."""
    if not SECRET_KEY_GLOBAL:
        raise ValueError("SECRET_KEY is not set. Run get_secret_key_from_input() first.")
    return hashlib.md5(SECRET_KEY_GLOBAL + message).hexdigest()

def verify(message: bytes, mac: str) -> bool:
    """Verifies if the given MAC is valid for the message."""
    expected_mac = generate_mac(message)
    print(f"    Inside verify - Expected MAC: {expected_mac}, Received MAC: {mac}")
    return mac == expected_mac

def main():
    print("--- Server Setup ---")
    get_secret_key_from_input()

    original_message_str = input("Enter the original message string (e.g., amount=100&to=alice): ")
    original_message_bytes = original_message_str.encode('utf-8')

    original_mac = generate_mac(original_message_bytes)

    print("\\n=== Server Initial Output (for client.py) ===")
    print(f"Using SECRET_KEY: {SECRET_KEY_GLOBAL.decode()} (length: {len(SECRET_KEY_GLOBAL)})")
    print(f"Original message: {original_message_bytes.decode()}")
    print(f"Generated Original MAC: {original_mac} <--- Attacker: Note this MAC and Secret Key Length for client.py")

    print("\\n--- Verifying legitimate message (self-check) ---")
    if verify(original_message_bytes, original_mac):
        print("Legitimate MAC verified successfully. Message is authentic.\\n")
    else:
        print("Error: Legitimate MAC verification failed (unexpected).\\n")

    # --- Section to test the attacker's forged message ---
    print("\\n--- Server: Awaiting Attacker's Forged Message and MAC ---")
    print("You will now input the forged data presumably generated by client.py.")

    while True:
        forged_message_hex_str = input("Enter the Forged Message for Server (as HEX string from client.py output): ")
        try:
            attacker_forged_message_bytes = bytes.fromhex(forged_message_hex_str)
            break
        except ValueError:
            print("Invalid hex string. Please ensure you copy the hex representation correctly.")

    attacker_forged_mac_hex = input("Enter the Forged MAC (hex string from client.py output): ")

    print("\\n--- Verifying Attacker's Forged Message (from client.py) ---")
    print(f"Attempting to verify forged message (bytes, from hex): {attacker_forged_message_bytes}")
    print(f"With forged MAC: {attacker_forged_mac_hex}")

    if verify(attacker_forged_message_bytes, attacker_forged_mac_hex):
        print("\\n>>> ATTACK SUCCESSFUL: Server accepted the attacker's forged message and MAC!")
    else:
        print("\\n>>> Attack Failed: Server rejected the attacker's forged message.")

if __name__ == "__main__":
    main()
